### ISSUE TITLE
推理结果中没有看到SAM分割的边缘

### ISSUE THREAD

**Issue by liangyijian1** [lyxlplhy/Sam2Onnx_Inference#1]
运行sam2()后，结果只有个红色的目标框，并没有分割结果显示，求助！！

**Comment by lyxlplhy** [comment]
首先判断模型是否加载成功，然后推理方式是用框还是点作为提示信息需要确认，框的输入格式为xywh，点为xy需要确认是否正确

**Comment by lyxlplhy** [comment]
> 运行sam2()后，结果只有个红色的目标框，并没有分割结果显示，求助！！

首先判断模型是否加载成功，然后推理方式是用框还是点作为提示信息需要确认，框的输入格式为xywh，点为xy需要确认是否正确。然后sam2函数中我测试函数较为粗糙，你需要看明白imraed图像的地方
